# Generated by Django 3.2.4 on 2021-07-05 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadprofile',
            name='loads',
        ),
        migrations.AddField(
            model_name='load',
            name='load_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.loadprofile'),
        ),
    ]
