# Generated by Django 3.2.4 on 2021-07-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_auto_20210705_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadprofile',
            name='total_demand',
            field=models.FloatField(default=0),
        ),
    ]
