# Generated by Django 3.2.4 on 2021-07-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_loadprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadprofile',
            name='name',
            field=models.CharField(default='Some', max_length=120),
            preserve_default=False,
        ),
    ]
