# Generated by Django 3.2.4 on 2021-07-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_alter_load_load_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='total_usage',
            new_name='total_wattage_hourly',
        ),
        migrations.AddField(
            model_name='loadprofile',
            name='array_sizing',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loadprofile',
            name='battery_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loadprofile',
            name='cable_sizing',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loadprofile',
            name='inverter_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loadprofile',
            name='no_of_panels',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loadprofile',
            name='panel_output',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loadprofile',
            name='peak_sun_hours',
            field=models.FloatField(default=3.5),
        ),
        migrations.AlterField(
            model_name='load',
            name='inverter_efficiency',
            field=models.FloatField(blank=True, default=0.9, null=True),
        ),
    ]
