# Generated by Django 3.2.4 on 2021-07-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_loadprofile_inverter_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadprofile',
            name='inverter_efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
