# Generated by Django 3.2.4 on 2021-07-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0010_alter_loadprofile_inverter_efficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('isc', models.IntegerField(verbose_name='Short circuit current')),
                ('pveff', models.IntegerField(verbose_name='PV efficiency')),
                ('beff', models.IntegerField(verbose_name='Battery efficiency')),
                ('power_rating', models.IntegerField()),
                ('plan_file', models.FileField(upload_to='')),
                ('peak_generation_factor', models.IntegerField()),
            ],
        ),
    ]
