# Generated by Django 3.2.4 on 2021-07-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_solarmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarmodel',
            name='beff',
        ),
        migrations.AddField(
            model_name='solarmodel',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
