# Generated by Django 3.2.4 on 2021-07-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0012_auto_20210730_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='solarmodel',
            name='plan_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
