# Generated by Django 3.2.4 on 2021-07-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0013_auto_20210730_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarmodel',
            name='isc',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Short circuit current'),
        ),
        migrations.AlterField(
            model_name='solarmodel',
            name='peak_generation_factor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='solarmodel',
            name='pveff',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PV efficiency'),
        ),
    ]
