# Generated by Django 3.2.4 on 2021-07-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0014_auto_20210730_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadprofile',
            name='total_ac_demand',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='loadprofile',
            name='total_dc_demand',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='loadprofile',
            name='total_demand',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
